version: "3.8"
services:
  app:
    image: ${DOCKER_REPO}/${DOCKER_IMAGE}:latest # Docker Hub 이미지
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: ${DATABASE_HOST}
      MYSQL_ROOT_PASSWORD: ${DATABASE_HOST_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci